#FROM golang:1.14-alpine AS build

#WORKDIR /app/
#COPY full-cycle.go go.* /app/
#RUN CGO_ENABLED=0 go build -o /bin/demo

#FROM scratch
#COPY --from=build /bin/demo /bin/demo
#ENTRYPOINT ["/bin/demo/"]


FROM golang:1.14-alpine AS builder

WORKDIR /go/src/app

COPY ./full-cycle.go .

RUN go build -ldflags '-s -w' full-cycle.go

FROM scratch

WORKDIR /app

COPY --from=builder /go/src/app / 

CMD ["/full-cycle"]