FROM golang:1.12-alpine as builder

WORKDIR /go/src/app

COPY go.mod ./
COPY go.sum ./

#RUN go mod download

COPY ./full-cycle.go .

#RUN go build -o /full-cycle.go
RUN go build -ldflags '-s -w' full-cycle.go


FROM scratch
WORKDIR /app
COPY --from=builder . /go/src/app /

EXPOSE 8080

CMD ["/full-cycle.go"]




